apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: my-vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
      app.kubernetes.io/instance: vault
      component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault
        app.kubernetes.io/instance: vault
        component: server
    spec:
      serviceAccountName: my-vault
      containers:
        - name: vault
          image: hashicorp/vault:1.13.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8200
              name: http
