apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: first
spec:
  cidr: 192.168.2.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: itmo == "first"
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: second
spec:
  cidr: 192.168.1.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: itmo == "second"