apiVersion: v1
kind: Service
metadata:
  name: itmo-frontend
  namespace: itmo-frontend
  labels:
    app: itmo-frontend
spec:
  type: NodePort
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: itmo-frontend